apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: {{ .Values.mysql.namespace }}
spec:
  type: {{ .Values.mysql.service.type }}
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP

