apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}    
    targetPort: {{ .Values.app.port }}  
  type: {{ .Values.service.type }}















