
{{- if .Values.initdb.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: {{ .Values.mysql.namespace }}

data:
  MYSQL_DATABASE: {{ .Values.mysql.database }}
  init.sql: |
{{ .Values.initdb.script | indent 4 }}
{{- end}}
