apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secret
  namespace: {{ .Values.app.namespace }}
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: {{ .Values.spring.datasource.password | b64enc | quote }}  # 64Base 인코딩 
