apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
  labels:
    app: {{ .Values.app.name }}
spec:
  ports:
    - port: 8080
      targetPort: {{ .Values.app.port }} 
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.app.name }}
















