apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.app.name }}-rolebinding
  namespace: {{ .Values.app.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.app.name }}-sa
    namespace: {{ .Values.app.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.app.name }}-role
  apiGroup: rbac.authorization.k8s.io

