app:
  namespace: shopmall
  name: item-service-api
  replicas: 1
  image: javaenjoy0714/item-service:latest
  port: 11000
  
  resources: {}
  
  # resources:
  #  requests:
  #    cpu: 300m
  #    memory: 256Mi
  #  limits:
  #    cpu: 300m
  #    memory: 500Mi

podLabels:
  tier: backend

probes:
  readiness: {}
  liveness: {}
  
# probes:
#  readiness:
#      httpGet:
#      path: /actuator/health/readiness
#      port: 9000
#    initialDelaySeconds: 10
#    periodSeconds: 10
#  liveness:
#    httpGet:
#      path: /actuator/health/liveness
#      port: 9000
#    initialDelaySeconds: 120
#    periodSeconds: 10


service:
  enabled: true
  type: ClusterIP
  port: 80


ingress:
  enabled: false
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  className: alb
  host: ""
  path: /
  pathType: Prefix


spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://mysql.shopmall.svc.cluster.local:3306/item_db?serverTimezone=Asia/Seoul&characterEncoding=utf8  
    username: root
    password: "1234"                        


























































































































